export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';

export const GET_SEARCH_MOVIES_BY_TITLE = 'GET_SEARCH_MOVIES_BY_TITLE';
export const GET_SEARCH_MOVIES_BY_GENGRE = 'GET_SEARCH_MOVIES_BY_GENGRE';

export const GET_ALL_MOVIES_BY_RELEASED_DATA = 'GET_ALL_MOVIES_BY_RELEASED_DATA';
export const GET_ALL_MOVIES_BY_RATING = 'GET_ALL_MOVIES_BY_RATING';

export const UPLOAD_MOVIES = 'UPLOAD_MOVIES';
export const UPLOAD_MOVIES_SUCCSESS = 'UPLOAD_MOVIES_SUCCSESS';
export const UPLOAD_MOVIES_FAILED = 'UPLOAD_MOVIES_FAILED';

export const UPLOAD_SEARCH_MOVIES = 'UPLOAD_SEARCH_MOVIES';
export const UPLOAD_SEARCH_MOVIES_SUCCSESS = 'UPLOAD_SEARCH_MOVIES_SUCCSESS';
export const UPLOAD_SEARCH_MOVIES_FAILED = 'UPLOAD_SEARCH_MOVIES_FAILED';