export const UPLOAD_MOVIES = 'UPLOAD_MOVIES';
export const UPLOAD_MOVIES_SUCCSESS = 'UPLOAD_MOVIES_SUCCSESS';
export const UPLOAD_MOVIES_FAILED = 'UPLOAD_MOVIES_FAILED';

export const UPLOAD_ID_MOVIE = 'UPLOAD_ID_MOVIE';
export const UPLOAD_ID_MOVIE_SUCCSESS = 'UPLOAD_ID_MOVIE_SUCCSESS';
export const UPLOAD_ID_MOVIE_FAILED = 'UPLOAD_ID_MOVIE_FAILED';
export const DISABLE_DESCRIPTION_MODE = 'DISABLE_DESCRIPTION_MODE';

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';